name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: release
          retention-days: 5
